version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/reactapp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/ml-service"
    schedule:
      interval: "weekly"
