apiVersion: v1
kind: Service
metadata:
  name: wealthgenie-frontend
  namespace: wealthgenie
  labels:
    app: wealthgenie-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: wealthgenie-frontend