apiVersion: v1
kind: Service
metadata:
  name: wealthgenie-ml-service
  namespace: wealthgenie
  labels:
    app: wealthgenie-ml-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: wealthgenie-ml-service
