apiVersion: v1
kind: Service
metadata:
  name: wealthgenie-server
  namespace: wealthgenie
  labels:
    app: wealthgenie-server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: wealthgenie-server
